/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as authPagesRouteRouteImport } from './routes/(auth-pages)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicTermsRouteImport } from './routes/(public)/terms'
import { Route as publicSuccessRouteImport } from './routes/(public)/success'
import { Route as publicPrivacyRouteImport } from './routes/(public)/privacy'
import { Route as publicPricingRouteImport } from './routes/(public)/pricing'
import { Route as authPagesSignupRouteImport } from './routes/(auth-pages)/signup'
import { Route as authPagesLoginRouteImport } from './routes/(auth-pages)/login'
import { Route as authenticatedDashboardRouteRouteImport } from './routes/(authenticated)/dashboard/route'
import { Route as publicDocsIndexRouteImport } from './routes/(public)/docs/index'
import { Route as authenticatedDashboardIndexRouteImport } from './routes/(authenticated)/dashboard/index'
import { Route as ApiFSlugRouteImport } from './routes/api/f/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authenticatedDashboardSettingsRouteImport } from './routes/(authenticated)/dashboard/settings'
import { Route as authenticatedDashboardAdminRouteRouteImport } from './routes/(authenticated)/dashboard/admin/route'
import { Route as publicDocsTemplatesIndexRouteImport } from './routes/(public)/docs/templates/index'
import { Route as authenticatedDashboardFormsIndexRouteImport } from './routes/(authenticated)/dashboard/forms/index'
import { Route as authenticatedDashboardAdminIndexRouteImport } from './routes/(authenticated)/dashboard/admin/index'
import { Route as publicDocsTemplatesWaitingListRouteImport } from './routes/(public)/docs/templates/waiting-list'
import { Route as publicDocsTemplatesNewsletterRouteImport } from './routes/(public)/docs/templates/newsletter'
import { Route as publicDocsTemplatesFeedbackRouteImport } from './routes/(public)/docs/templates/feedback'
import { Route as publicDocsTemplatesContactRouteImport } from './routes/(public)/docs/templates/contact'
import { Route as publicDocsTemplatesBugReportRouteImport } from './routes/(public)/docs/templates/bug-report'
import { Route as authenticatedDashboardFormsNewRouteImport } from './routes/(authenticated)/dashboard/forms/new'
import { Route as authenticatedDashboardFormsFormIdIndexRouteImport } from './routes/(authenticated)/dashboard/forms/$formId/index'
import { Route as authenticatedDashboardAdminStatisticsIndexRouteImport } from './routes/(authenticated)/dashboard/admin/statistics/index'
import { Route as authenticatedDashboardFormsFormIdNotificationsRouteImport } from './routes/(authenticated)/dashboard/forms/$formId/notifications'
import { Route as authenticatedDashboardFormsFormIdEditRouteImport } from './routes/(authenticated)/dashboard/forms/$formId/edit'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const authPagesRouteRoute = authPagesRouteRouteImport.update({
  id: '/(auth-pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicTermsRoute = publicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicSuccessRoute = publicSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPrivacyRoute = publicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicPricingRoute = publicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => publicRouteRoute,
} as any)
const authPagesSignupRoute = authPagesSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authPagesRouteRoute,
} as any)
const authenticatedDashboardRouteRoute =
  authenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const publicDocsIndexRoute = publicDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authenticatedDashboardIndexRoute =
  authenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const ApiFSlugRoute = ApiFSlugRouteImport.update({
  id: '/api/f/$slug',
  path: '/api/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardSettingsRoute =
  authenticatedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminRouteRoute =
  authenticatedDashboardAdminRouteRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const publicDocsTemplatesIndexRoute =
  publicDocsTemplatesIndexRouteImport.update({
    id: '/docs/templates/',
    path: '/docs/templates/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const authenticatedDashboardFormsIndexRoute =
  authenticatedDashboardFormsIndexRouteImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminIndexRoute =
  authenticatedDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedDashboardAdminRouteRoute,
  } as any)
const publicDocsTemplatesWaitingListRoute =
  publicDocsTemplatesWaitingListRouteImport.update({
    id: '/docs/templates/waiting-list',
    path: '/docs/templates/waiting-list',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicDocsTemplatesNewsletterRoute =
  publicDocsTemplatesNewsletterRouteImport.update({
    id: '/docs/templates/newsletter',
    path: '/docs/templates/newsletter',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicDocsTemplatesFeedbackRoute =
  publicDocsTemplatesFeedbackRouteImport.update({
    id: '/docs/templates/feedback',
    path: '/docs/templates/feedback',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicDocsTemplatesContactRoute =
  publicDocsTemplatesContactRouteImport.update({
    id: '/docs/templates/contact',
    path: '/docs/templates/contact',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicDocsTemplatesBugReportRoute =
  publicDocsTemplatesBugReportRouteImport.update({
    id: '/docs/templates/bug-report',
    path: '/docs/templates/bug-report',
    getParentRoute: () => publicRouteRoute,
  } as any)
const authenticatedDashboardFormsNewRoute =
  authenticatedDashboardFormsNewRouteImport.update({
    id: '/forms/new',
    path: '/forms/new',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardFormsFormIdIndexRoute =
  authenticatedDashboardFormsFormIdIndexRouteImport.update({
    id: '/forms/$formId/',
    path: '/forms/$formId/',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardAdminStatisticsIndexRoute =
  authenticatedDashboardAdminStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => authenticatedDashboardAdminRouteRoute,
  } as any)
const authenticatedDashboardFormsFormIdNotificationsRoute =
  authenticatedDashboardFormsFormIdNotificationsRouteImport.update({
    id: '/forms/$formId/notifications',
    path: '/forms/$formId/notifications',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)
const authenticatedDashboardFormsFormIdEditRoute =
  authenticatedDashboardFormsFormIdEditRouteImport.update({
    id: '/forms/$formId/edit',
    path: '/forms/$formId/edit',
    getParentRoute: () => authenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/pricing': typeof publicPricingRoute
  '/privacy': typeof publicPrivacyRoute
  '/success': typeof publicSuccessRoute
  '/terms': typeof publicTermsRoute
  '/': typeof publicIndexRoute
  '/dashboard/admin': typeof authenticatedDashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof authenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/dashboard/': typeof authenticatedDashboardIndexRoute
  '/docs/': typeof publicDocsIndexRoute
  '/dashboard/forms/new': typeof authenticatedDashboardFormsNewRoute
  '/docs/templates/bug-report': typeof publicDocsTemplatesBugReportRoute
  '/docs/templates/contact': typeof publicDocsTemplatesContactRoute
  '/docs/templates/feedback': typeof publicDocsTemplatesFeedbackRoute
  '/docs/templates/newsletter': typeof publicDocsTemplatesNewsletterRoute
  '/docs/templates/waiting-list': typeof publicDocsTemplatesWaitingListRoute
  '/dashboard/admin/': typeof authenticatedDashboardAdminIndexRoute
  '/dashboard/forms/': typeof authenticatedDashboardFormsIndexRoute
  '/docs/templates/': typeof publicDocsTemplatesIndexRoute
  '/dashboard/forms/$formId/edit': typeof authenticatedDashboardFormsFormIdEditRoute
  '/dashboard/forms/$formId/notifications': typeof authenticatedDashboardFormsFormIdNotificationsRoute
  '/dashboard/admin/statistics/': typeof authenticatedDashboardAdminStatisticsIndexRoute
  '/dashboard/forms/$formId/': typeof authenticatedDashboardFormsFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authPagesLoginRoute
  '/signup': typeof authPagesSignupRoute
  '/pricing': typeof publicPricingRoute
  '/privacy': typeof publicPrivacyRoute
  '/success': typeof publicSuccessRoute
  '/terms': typeof publicTermsRoute
  '/': typeof publicIndexRoute
  '/dashboard/settings': typeof authenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/dashboard': typeof authenticatedDashboardIndexRoute
  '/docs': typeof publicDocsIndexRoute
  '/dashboard/forms/new': typeof authenticatedDashboardFormsNewRoute
  '/docs/templates/bug-report': typeof publicDocsTemplatesBugReportRoute
  '/docs/templates/contact': typeof publicDocsTemplatesContactRoute
  '/docs/templates/feedback': typeof publicDocsTemplatesFeedbackRoute
  '/docs/templates/newsletter': typeof publicDocsTemplatesNewsletterRoute
  '/docs/templates/waiting-list': typeof publicDocsTemplatesWaitingListRoute
  '/dashboard/admin': typeof authenticatedDashboardAdminIndexRoute
  '/dashboard/forms': typeof authenticatedDashboardFormsIndexRoute
  '/docs/templates': typeof publicDocsTemplatesIndexRoute
  '/dashboard/forms/$formId/edit': typeof authenticatedDashboardFormsFormIdEditRoute
  '/dashboard/forms/$formId/notifications': typeof authenticatedDashboardFormsFormIdNotificationsRoute
  '/dashboard/admin/statistics': typeof authenticatedDashboardAdminStatisticsIndexRoute
  '/dashboard/forms/$formId': typeof authenticatedDashboardFormsFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth-pages)': typeof authPagesRouteRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(authenticated)/dashboard': typeof authenticatedDashboardRouteRouteWithChildren
  '/(auth-pages)/login': typeof authPagesLoginRoute
  '/(auth-pages)/signup': typeof authPagesSignupRoute
  '/(public)/pricing': typeof publicPricingRoute
  '/(public)/privacy': typeof publicPrivacyRoute
  '/(public)/success': typeof publicSuccessRoute
  '/(public)/terms': typeof publicTermsRoute
  '/(public)/': typeof publicIndexRoute
  '/(authenticated)/dashboard/admin': typeof authenticatedDashboardAdminRouteRouteWithChildren
  '/(authenticated)/dashboard/settings': typeof authenticatedDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/f/$slug': typeof ApiFSlugRoute
  '/(authenticated)/dashboard/': typeof authenticatedDashboardIndexRoute
  '/(public)/docs/': typeof publicDocsIndexRoute
  '/(authenticated)/dashboard/forms/new': typeof authenticatedDashboardFormsNewRoute
  '/(public)/docs/templates/bug-report': typeof publicDocsTemplatesBugReportRoute
  '/(public)/docs/templates/contact': typeof publicDocsTemplatesContactRoute
  '/(public)/docs/templates/feedback': typeof publicDocsTemplatesFeedbackRoute
  '/(public)/docs/templates/newsletter': typeof publicDocsTemplatesNewsletterRoute
  '/(public)/docs/templates/waiting-list': typeof publicDocsTemplatesWaitingListRoute
  '/(authenticated)/dashboard/admin/': typeof authenticatedDashboardAdminIndexRoute
  '/(authenticated)/dashboard/forms/': typeof authenticatedDashboardFormsIndexRoute
  '/(public)/docs/templates/': typeof publicDocsTemplatesIndexRoute
  '/(authenticated)/dashboard/forms/$formId/edit': typeof authenticatedDashboardFormsFormIdEditRoute
  '/(authenticated)/dashboard/forms/$formId/notifications': typeof authenticatedDashboardFormsFormIdNotificationsRoute
  '/(authenticated)/dashboard/admin/statistics/': typeof authenticatedDashboardAdminStatisticsIndexRoute
  '/(authenticated)/dashboard/forms/$formId/': typeof authenticatedDashboardFormsFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/pricing'
    | '/privacy'
    | '/success'
    | '/terms'
    | '/'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/f/$slug'
    | '/dashboard/'
    | '/docs/'
    | '/dashboard/forms/new'
    | '/docs/templates/bug-report'
    | '/docs/templates/contact'
    | '/docs/templates/feedback'
    | '/docs/templates/newsletter'
    | '/docs/templates/waiting-list'
    | '/dashboard/admin/'
    | '/dashboard/forms/'
    | '/docs/templates/'
    | '/dashboard/forms/$formId/edit'
    | '/dashboard/forms/$formId/notifications'
    | '/dashboard/admin/statistics/'
    | '/dashboard/forms/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/pricing'
    | '/privacy'
    | '/success'
    | '/terms'
    | '/'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/f/$slug'
    | '/dashboard'
    | '/docs'
    | '/dashboard/forms/new'
    | '/docs/templates/bug-report'
    | '/docs/templates/contact'
    | '/docs/templates/feedback'
    | '/docs/templates/newsletter'
    | '/docs/templates/waiting-list'
    | '/dashboard/admin'
    | '/dashboard/forms'
    | '/docs/templates'
    | '/dashboard/forms/$formId/edit'
    | '/dashboard/forms/$formId/notifications'
    | '/dashboard/admin/statistics'
    | '/dashboard/forms/$formId'
  id:
    | '__root__'
    | '/(auth-pages)'
    | '/(authenticated)'
    | '/(public)'
    | '/(authenticated)/dashboard'
    | '/(auth-pages)/login'
    | '/(auth-pages)/signup'
    | '/(public)/pricing'
    | '/(public)/privacy'
    | '/(public)/success'
    | '/(public)/terms'
    | '/(public)/'
    | '/(authenticated)/dashboard/admin'
    | '/(authenticated)/dashboard/settings'
    | '/api/auth/$'
    | '/api/f/$slug'
    | '/(authenticated)/dashboard/'
    | '/(public)/docs/'
    | '/(authenticated)/dashboard/forms/new'
    | '/(public)/docs/templates/bug-report'
    | '/(public)/docs/templates/contact'
    | '/(public)/docs/templates/feedback'
    | '/(public)/docs/templates/newsletter'
    | '/(public)/docs/templates/waiting-list'
    | '/(authenticated)/dashboard/admin/'
    | '/(authenticated)/dashboard/forms/'
    | '/(public)/docs/templates/'
    | '/(authenticated)/dashboard/forms/$formId/edit'
    | '/(authenticated)/dashboard/forms/$formId/notifications'
    | '/(authenticated)/dashboard/admin/statistics/'
    | '/(authenticated)/dashboard/forms/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authPagesRouteRoute: typeof authPagesRouteRouteWithChildren
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFSlugRoute: typeof ApiFSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth-pages)': {
      id: '/(auth-pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authPagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/terms': {
      id: '/(public)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/success': {
      id: '/(public)/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof publicSuccessRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/privacy': {
      id: '/(public)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof publicPrivacyRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/pricing': {
      id: '/(public)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof publicPricingRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth-pages)/signup': {
      id: '/(auth-pages)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authPagesSignupRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(auth-pages)/login': {
      id: '/(auth-pages)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authPagesLoginRouteImport
      parentRoute: typeof authPagesRouteRoute
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(public)/docs/': {
      id: '/(public)/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof publicDocsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/dashboard/': {
      id: '/(authenticated)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof authenticatedDashboardIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/api/f/$slug': {
      id: '/api/f/$slug'
      path: '/api/f/$slug'
      fullPath: '/api/f/$slug'
      preLoaderRoute: typeof ApiFSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard/settings': {
      id: '/(authenticated)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof authenticatedDashboardSettingsRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin': {
      id: '/(authenticated)/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof authenticatedDashboardAdminRouteRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(public)/docs/templates/': {
      id: '/(public)/docs/templates/'
      path: '/docs/templates'
      fullPath: '/docs/templates/'
      preLoaderRoute: typeof publicDocsTemplatesIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/dashboard/forms/': {
      id: '/(authenticated)/dashboard/forms/'
      path: '/forms'
      fullPath: '/dashboard/forms/'
      preLoaderRoute: typeof authenticatedDashboardFormsIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/': {
      id: '/(authenticated)/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof authenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof authenticatedDashboardAdminRouteRoute
    }
    '/(public)/docs/templates/waiting-list': {
      id: '/(public)/docs/templates/waiting-list'
      path: '/docs/templates/waiting-list'
      fullPath: '/docs/templates/waiting-list'
      preLoaderRoute: typeof publicDocsTemplatesWaitingListRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/docs/templates/newsletter': {
      id: '/(public)/docs/templates/newsletter'
      path: '/docs/templates/newsletter'
      fullPath: '/docs/templates/newsletter'
      preLoaderRoute: typeof publicDocsTemplatesNewsletterRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/docs/templates/feedback': {
      id: '/(public)/docs/templates/feedback'
      path: '/docs/templates/feedback'
      fullPath: '/docs/templates/feedback'
      preLoaderRoute: typeof publicDocsTemplatesFeedbackRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/docs/templates/contact': {
      id: '/(public)/docs/templates/contact'
      path: '/docs/templates/contact'
      fullPath: '/docs/templates/contact'
      preLoaderRoute: typeof publicDocsTemplatesContactRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/docs/templates/bug-report': {
      id: '/(public)/docs/templates/bug-report'
      path: '/docs/templates/bug-report'
      fullPath: '/docs/templates/bug-report'
      preLoaderRoute: typeof publicDocsTemplatesBugReportRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(authenticated)/dashboard/forms/new': {
      id: '/(authenticated)/dashboard/forms/new'
      path: '/forms/new'
      fullPath: '/dashboard/forms/new'
      preLoaderRoute: typeof authenticatedDashboardFormsNewRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/forms/$formId/': {
      id: '/(authenticated)/dashboard/forms/$formId/'
      path: '/forms/$formId'
      fullPath: '/dashboard/forms/$formId/'
      preLoaderRoute: typeof authenticatedDashboardFormsFormIdIndexRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/admin/statistics/': {
      id: '/(authenticated)/dashboard/admin/statistics/'
      path: '/statistics'
      fullPath: '/dashboard/admin/statistics/'
      preLoaderRoute: typeof authenticatedDashboardAdminStatisticsIndexRouteImport
      parentRoute: typeof authenticatedDashboardAdminRouteRoute
    }
    '/(authenticated)/dashboard/forms/$formId/notifications': {
      id: '/(authenticated)/dashboard/forms/$formId/notifications'
      path: '/forms/$formId/notifications'
      fullPath: '/dashboard/forms/$formId/notifications'
      preLoaderRoute: typeof authenticatedDashboardFormsFormIdNotificationsRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
    '/(authenticated)/dashboard/forms/$formId/edit': {
      id: '/(authenticated)/dashboard/forms/$formId/edit'
      path: '/forms/$formId/edit'
      fullPath: '/dashboard/forms/$formId/edit'
      preLoaderRoute: typeof authenticatedDashboardFormsFormIdEditRouteImport
      parentRoute: typeof authenticatedDashboardRouteRoute
    }
  }
}

interface authPagesRouteRouteChildren {
  authPagesLoginRoute: typeof authPagesLoginRoute
  authPagesSignupRoute: typeof authPagesSignupRoute
}

const authPagesRouteRouteChildren: authPagesRouteRouteChildren = {
  authPagesLoginRoute: authPagesLoginRoute,
  authPagesSignupRoute: authPagesSignupRoute,
}

const authPagesRouteRouteWithChildren = authPagesRouteRoute._addFileChildren(
  authPagesRouteRouteChildren,
)

interface authenticatedDashboardAdminRouteRouteChildren {
  authenticatedDashboardAdminIndexRoute: typeof authenticatedDashboardAdminIndexRoute
  authenticatedDashboardAdminStatisticsIndexRoute: typeof authenticatedDashboardAdminStatisticsIndexRoute
}

const authenticatedDashboardAdminRouteRouteChildren: authenticatedDashboardAdminRouteRouteChildren =
  {
    authenticatedDashboardAdminIndexRoute:
      authenticatedDashboardAdminIndexRoute,
    authenticatedDashboardAdminStatisticsIndexRoute:
      authenticatedDashboardAdminStatisticsIndexRoute,
  }

const authenticatedDashboardAdminRouteRouteWithChildren =
  authenticatedDashboardAdminRouteRoute._addFileChildren(
    authenticatedDashboardAdminRouteRouteChildren,
  )

interface authenticatedDashboardRouteRouteChildren {
  authenticatedDashboardAdminRouteRoute: typeof authenticatedDashboardAdminRouteRouteWithChildren
  authenticatedDashboardSettingsRoute: typeof authenticatedDashboardSettingsRoute
  authenticatedDashboardIndexRoute: typeof authenticatedDashboardIndexRoute
  authenticatedDashboardFormsNewRoute: typeof authenticatedDashboardFormsNewRoute
  authenticatedDashboardFormsIndexRoute: typeof authenticatedDashboardFormsIndexRoute
  authenticatedDashboardFormsFormIdEditRoute: typeof authenticatedDashboardFormsFormIdEditRoute
  authenticatedDashboardFormsFormIdNotificationsRoute: typeof authenticatedDashboardFormsFormIdNotificationsRoute
  authenticatedDashboardFormsFormIdIndexRoute: typeof authenticatedDashboardFormsFormIdIndexRoute
}

const authenticatedDashboardRouteRouteChildren: authenticatedDashboardRouteRouteChildren =
  {
    authenticatedDashboardAdminRouteRoute:
      authenticatedDashboardAdminRouteRouteWithChildren,
    authenticatedDashboardSettingsRoute: authenticatedDashboardSettingsRoute,
    authenticatedDashboardIndexRoute: authenticatedDashboardIndexRoute,
    authenticatedDashboardFormsNewRoute: authenticatedDashboardFormsNewRoute,
    authenticatedDashboardFormsIndexRoute:
      authenticatedDashboardFormsIndexRoute,
    authenticatedDashboardFormsFormIdEditRoute:
      authenticatedDashboardFormsFormIdEditRoute,
    authenticatedDashboardFormsFormIdNotificationsRoute:
      authenticatedDashboardFormsFormIdNotificationsRoute,
    authenticatedDashboardFormsFormIdIndexRoute:
      authenticatedDashboardFormsFormIdIndexRoute,
  }

const authenticatedDashboardRouteRouteWithChildren =
  authenticatedDashboardRouteRoute._addFileChildren(
    authenticatedDashboardRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRouteRoute: typeof authenticatedDashboardRouteRouteWithChildren
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRouteRoute:
    authenticatedDashboardRouteRouteWithChildren,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface publicRouteRouteChildren {
  publicPricingRoute: typeof publicPricingRoute
  publicPrivacyRoute: typeof publicPrivacyRoute
  publicSuccessRoute: typeof publicSuccessRoute
  publicTermsRoute: typeof publicTermsRoute
  publicIndexRoute: typeof publicIndexRoute
  publicDocsIndexRoute: typeof publicDocsIndexRoute
  publicDocsTemplatesBugReportRoute: typeof publicDocsTemplatesBugReportRoute
  publicDocsTemplatesContactRoute: typeof publicDocsTemplatesContactRoute
  publicDocsTemplatesFeedbackRoute: typeof publicDocsTemplatesFeedbackRoute
  publicDocsTemplatesNewsletterRoute: typeof publicDocsTemplatesNewsletterRoute
  publicDocsTemplatesWaitingListRoute: typeof publicDocsTemplatesWaitingListRoute
  publicDocsTemplatesIndexRoute: typeof publicDocsTemplatesIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicPricingRoute: publicPricingRoute,
  publicPrivacyRoute: publicPrivacyRoute,
  publicSuccessRoute: publicSuccessRoute,
  publicTermsRoute: publicTermsRoute,
  publicIndexRoute: publicIndexRoute,
  publicDocsIndexRoute: publicDocsIndexRoute,
  publicDocsTemplatesBugReportRoute: publicDocsTemplatesBugReportRoute,
  publicDocsTemplatesContactRoute: publicDocsTemplatesContactRoute,
  publicDocsTemplatesFeedbackRoute: publicDocsTemplatesFeedbackRoute,
  publicDocsTemplatesNewsletterRoute: publicDocsTemplatesNewsletterRoute,
  publicDocsTemplatesWaitingListRoute: publicDocsTemplatesWaitingListRoute,
  publicDocsTemplatesIndexRoute: publicDocsTemplatesIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authPagesRouteRoute: authPagesRouteRouteWithChildren,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFSlugRoute: ApiFSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
